### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by oshcon**
Mavenized the project, updated everything to support the latest version of ProjectKorra (1.8.2), and added a simple implementation of LibsDisguises to give bending mobs skins - with config options of course!

### CODE REVIEW

**Comment by oshcon** [comment]
[ProjectKorraMobs.zip](https://github.com/jedk1/ProjectKorraMobs/files/751326/ProjectKorraMobs.zip)

Attached is a compiled copy of these changes, for testing.

**Comment by jedk1** [comment]
This looks cool. If I get time then I'll merge it.

**Comment by oshcon** [comment]
Awesome!

**Comment by jedk1** [comment]
So because I've never really used LibsDisguises in a plugin, care to explain to me what does what? The code looks quite different to what I'm used to so it would be nice to learn what does what :D

**Comment by oshcon** [comment]
Certainly. I've added Compatibility.java to this project as a means to "hook" into other plugins, such as LibsDisguises. Then, ensuring a compatible version of LibsDisguises is loaded, assignDisguise(Entity entity) in MobMethods.java then creates a PlayerDisguise object (which requires ProtocolLib's wrappers faux server packets and player components). Then using the static method disguiseEntity(Entity entity) from DisguiseAPI.java in LibsDisguises, the chosen entity is given the PlayerDisguise object we constructed just before. Since there are ways the disguise can be lost, like unloading chunks and stuff, I threw in a couple of things in MobListener.java. Also cancelled the Combust event for disguised zombies in daylight (will probably add a config option for this), and also added a percent chance to spawn a bending mob instead of just replacing all Zombies, Villagers, or Pigmen (just something I needed on my own server). None of the actual behavior, besides the bursting into flames in daylight, dropping items on death, and picking up dropped items, was changed, just how they look. 

Also, I added Spirit mobs as a gimmick for my own server. It just spawns a Vex disguised as a ShulkerBullet named Spirit whenever a bending mob dies. :)

**Comment by jedk1** [comment]
Oh thats actually really cool, I will certainly merge when I'm next at a wifi connection thats greater than the power of a potato.

**Comment by oshcon** [comment]
Thanks! LibsDisguises can be really fun to mess around with. lol

**Pull request merged**
